INSERT INTO "user" (username, first_name, last_name, email, birthdate, password, university, gender, role) VALUES ('learner1', 'First1', 'Last1', 'learner1@example.com',  '1994-07-16', 'password1', 'University A', 'male', 'learner') RETURNING id;
INSERT INTO "user" (username, first_name, last_name, email, birthdate, password, university, gender, role) VALUES ('learner2', 'First2', 'Last2', 'learner2@example.com',  '1982-12-02', 'password2', 'University A', 'female', 'learner') RETURNING id;
INSERT INTO "user" (username, first_name, last_name, email, birthdate, password, university, gender, role) VALUES ('learner3', 'First3', 'Last3', 'learner3@example.com',  '1997-07-31', 'password3', 'University A', 'female', 'learner') RETURNING id;
INSERT INTO "user" (username, first_name, last_name, email, birthdate, password, university, gender, role) VALUES ('learner4', 'First4', 'Last4', 'learner4@example.com',  '1987-05-01', 'password4', 'University A', 'male', 'learner') RETURNING id;
INSERT INTO "user" (username, first_name, last_name, email, birthdate, password, university, gender, role) VALUES ('learner5', 'First5', 'Last5', 'learner5@example.com',  '1982-01-21', 'password5', 'University A', 'male', 'learner') RETURNING id;
INSERT INTO "user" (username, first_name, last_name, email, birthdate, password, university, gender, role) VALUES ('learner6', 'First6', 'Last6', 'learner6@example.com',  '1987-08-02', 'password6', 'University A', 'female', 'learner') RETURNING id;
INSERT INTO "user" (username, first_name, last_name, email, birthdate, password, university, gender, role) VALUES ('learner7', 'First7', 'Last7', 'learner7@example.com',  '1996-01-18', 'password7', 'University A', 'female', 'learner') RETURNING id;
INSERT INTO "user" (username, first_name, last_name, email, birthdate, password, university, gender, role) VALUES ('learner8', 'First8', 'Last8', 'learner8@example.com',  '1998-04-20', 'password8', 'University A', 'male', 'learner') RETURNING id;
INSERT INTO "user" (username, first_name, last_name, email, birthdate, password, university, gender, role) VALUES ('learner9', 'First9', 'Last9', 'learner9@example.com',  '1980-10-01', 'password9', 'University A', 'male', 'learner') RETURNING id;
INSERT INTO "user" (username, first_name, last_name, email, birthdate, password, university, gender, role) VALUES ('learner10', 'First10', 'Last10', 'learner10@example.com',  '1983-10-23', 'password10', 'University A', 'female', 'learner') RETURNING id;
INSERT INTO "user" (username, first_name, last_name, email, birthdate, password, university, gender, role) VALUES ('learner11', 'First11', 'Last11', 'learner11@example.com',  '1989-11-22', 'password11', 'University A', 'female', 'learner') RETURNING id;
INSERT INTO "user" (username, first_name, last_name, email, birthdate, password, university, gender, role) VALUES ('learner12', 'First12', 'Last12', 'learner12@example.com',  '1982-03-25', 'password12', 'University A', 'female', 'learner') RETURNING id;
INSERT INTO "user" (username, first_name, last_name, email, birthdate, password, university, gender, role) VALUES ('learner13', 'First13', 'Last13', 'learner13@example.com',  '1988-10-17', 'password13', 'University A', 'male', 'learner') RETURNING id;
INSERT INTO "user" (username, first_name, last_name, email, birthdate, password, university, gender, role) VALUES ('learner14', 'First14', 'Last14', 'learner14@example.com',  '1997-02-05', 'password14', 'University A', 'female', 'learner') RETURNING id;
INSERT INTO "user" (username, first_name, last_name, email, birthdate, password, university, gender, role) VALUES ('learner15', 'First15', 'Last15', 'learner15@example.com',  '1984-09-13', 'password15', 'University A', 'female', 'learner') RETURNING id;
INSERT INTO "user" (username, first_name, last_name, email, birthdate, password, university, gender, role) VALUES ('tutor1', 'First1', 'Last1', 'tutor1@example.com',  '1983-05-13', 'password1', 'University A', 'female', 'tutor') RETURNING id;
INSERT INTO "user" (username, first_name, last_name, email, birthdate, password, university, gender, role) VALUES ('tutor2', 'First2', 'Last2', 'tutor2@example.com',  '1980-06-03', 'password2', 'University A', 'female', 'tutor') RETURNING id;
INSERT INTO "user" (username, first_name, last_name, email, birthdate, password, university, gender, role) VALUES ('tutor3', 'First3', 'Last3', 'tutor3@example.com',  '1987-10-09', 'password3', 'University A', 'female', 'tutor') RETURNING id;
INSERT INTO "user" (username, first_name, last_name, email, birthdate, password, university, gender, role) VALUES ('tutor4', 'First4', 'Last4', 'tutor4@example.com',  '1996-11-26', 'password4', 'University A', 'male', 'tutor') RETURNING id;
INSERT INTO "user" (username, first_name, last_name, email, birthdate, password, university, gender, role) VALUES ('tutor5', 'First5', 'Last5', 'tutor5@example.com',  '1985-09-28', 'password5', 'University A', 'male', 'tutor') RETURNING id;
INSERT INTO "learner" (user_id) VALUES (1);
INSERT INTO "learner" (user_id) VALUES (2);
INSERT INTO "learner" (user_id) VALUES (3);
INSERT INTO "learner" (user_id) VALUES (4);
INSERT INTO "learner" (user_id) VALUES (5);
INSERT INTO "learner" (user_id) VALUES (6);
INSERT INTO "learner" (user_id) VALUES (7);
INSERT INTO "learner" (user_id) VALUES (8);
INSERT INTO "learner" (user_id) VALUES (9);
INSERT INTO "learner" (user_id) VALUES (10);
INSERT INTO "learner" (user_id) VALUES (11);
INSERT INTO "learner" (user_id) VALUES (12);
INSERT INTO "learner" (user_id) VALUES (13);
INSERT INTO "learner" (user_id) VALUES (14);
INSERT INTO "learner" (user_id) VALUES (15);
INSERT INTO "tutor" (user_id, biography, available) VALUES (16, 'Biography for tutor1', True);
INSERT INTO "tutor" (user_id, biography, available) VALUES (17, 'Biography for tutor2', True);
INSERT INTO "tutor" (user_id, biography, available) VALUES (18, 'Biography for tutor3', False);
INSERT INTO "tutor" (user_id, biography, available) VALUES (19, 'Biography for tutor4', False);
INSERT INTO "tutor" (user_id, biography, available) VALUES (20, 'Biography for tutor5', False);