"""add a column to indicate if a meeting is done

Revision ID: 239d0705e4c9
Revises: 81ca41732682
Create Date: 2024-02-22 16:26:28.492261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '239d0705e4c9'
down_revision = '81ca41732682'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meeting', schema=None) as batch_op:
        batch_op.add_column(sa.Column('done', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meeting', schema=None) as batch_op:
        batch_op.drop_column('done')

    # ### end Alembic commands ###
